### ISSUE TITLE
performMinorGC not implemented

### ISSUE THREAD

**Issue by ivanperez-keera** [ghcjs/ghcjs-boot#32]
When I run a program that executes `performMinorGC`, the following is printed to the console:
```
index.html uncaught exception in Haskell main thread: ReferenceError: h$performGC is not defined rts.js:8792:7
```

**Comment by hamishmack** [comment]
This is still missing:

```Haskell
import System.Mem

main :: IO ()
main = do
      performMinorGC
      return ()
```

```
$ ghcjs --make test4.hs 
[1 of 1] Compiling Main             ( test4.hs, test4.js_o )
Linking test4.jsexe (Main)
$ node test4.jsexe/all.js
uncaught exception in Haskell main thread: ReferenceError: h$performGC is not defined
ReferenceError: h$performGC is not defined
    at h$$ac (/Users/hamish/haskell/issue88/test4.jsexe/all.js:26543:3)
    at h$runThreadSlice (/Users/hamish/haskell/issue88/test4.jsexe/all.js:9599:11)
    at h$runThreadSliceCatch (/Users/hamish/haskell/issue88/test4.jsexe/all.js:9545:12)
    at Object.h$mainLoop (/Users/hamish/haskell/issue88/test4.jsexe/all.js:9538:9)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
